
version: '3.8'

services:
  app:
    image: calculator-app-bonus:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"  # Map to your Spring Boot server port
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/calculatordb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculatordb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persisting the MySQL data

volumes:
  mysql_data:   # Named volume for database persistence
