apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service-bonus
spec:
  type: NodePort  # Use LoadBalancer to expose the service
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Port on the container
      nodePort: 30003
  selector:
    app: calculator-app-kubernetes-bonus

