apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  type: LoadBalancer # Use LoadBalancer to expose the service
  ports:
  - port: 80  # External port
    targetPort: 8080  # Port on the container
    nodePort: 30001
  selector:
    app: calculator-app-kubernetes

